name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: environments/dev
        run: |
          terraform init \
            -backend-config="resource_group_name=$BACKEND_RG" \
            -backend-config="storage_account_name=$BACKEND_SA" \
            -backend-config="container_name=$BACKEND_CONTAINER" \
            -backend-config="key=$BACKEND_KEY"
        env:
          BACKEND_RG: ${{ secrets.BACKEND_RG }}
          BACKEND_SA: ${{ secrets.BACKEND_SA }}
          BACKEND_CONTAINER: ${{ secrets.BACKEND_CONTAINER }}
          BACKEND_KEY: ${{ secrets.BACKEND_KEY }}

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
