location                = "East US"
resource_group          = "rg-aks-dev"
aks_name                = "aks-sre-dev"
dns_prefix              = "aksdev"
vnet_cidr               = "10.0.0.0/16"
subnet_cidr             = "10.0.1.0/24"
backend_resource_group  = "rg-tfstate"
backend_storage_account = "statestoragevinoth"
backend_container_name  = "tfstate"
backend_key             = "aks/dev/terraform.tfstate"
tags = {
  Environment = "dev"
  Owner       = "vinoth"
  Project     = "aks-sre"
  CostCenter  = "devops"
  CreatedBy   = "terraform"
}
